// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CGooglePlayServiceDefine
{
        public const string achievement_mother_of_bomb = "CgkIi9KKv58OEAIQBg"; // <GPGSID>
        public const string achievement_grenade_unlocked = "CgkIi9KKv58OEAIQAQ"; // <GPGSID>
        public const string achievement_dynamite_expert = "CgkIi9KKv58OEAIQAg"; // <GPGSID>
        public const string achievement_a_huge_explosion = "CgkIi9KKv58OEAIQBw"; // <GPGSID>
        public const string achievement_scientist = "CgkIi9KKv58OEAIQAw"; // <GPGSID>
        public const string achievement_big_picture = "CgkIi9KKv58OEAIQBQ"; // <GPGSID>
        public const string leaderboard_fly_away = "CgkIi9KKv58OEAIQCA"; // <GPGSID>
        public const string achievement_explosion = "CgkIi9KKv58OEAIQBA"; // <GPGSID>
        public const string achievement_demolitionist = "CgkIi9KKv58OEAIQAA"; // <GPGSID>

}

